### ISSUE TITLE
Details of manual labeling protocol, particularly for SN

### ISSUE THREAD

**Issue by stnava** [jmtyszka/CIT168-SubCorticalAtlas#2]
thank you so much for putting this resource together.   we are hoping to pilot some labeling strategies on some internal data and I am wondering if you have a little more detail to the manual protocol that you used.   either a white paper or just references to the "best" or "most reliable" MRI-based labeling protocol that you've found would be quite helpful.   just FYI, I did read that you used Allen + Paxinos resources but I was hoping there might be a little more info than what is shared here https://github.com/jmtyszka/CIT168-SubCorticalAtlas/wiki/Region-Deliniation 

just hoping to minimize the amount of effort in making errors / training labelers, etc.

many thanks for any feedback.

**Comment by jmtyszka** [comment]
Hi Brian - I'm equally grateful to you for the many years you've put into the development of ANTs. I don't have anything more detailed in hand, but I can upload a more detailed description of the approach we took to labeling the SN (and subcortical regions in general) to this repo. Stay tuned.

**Comment by jmtyszka** [comment]
Apologies for taking so long to get this uploaded. I've added some [slides with more detailed guidance](https://github.com/jmtyszka/CIT168-SubCorticalAtlas/blob/master/Documentation/Labeling_the_Substantia_Nigra.pdf) on how to label the SN in the CIT168 T1w and T2w templates to the repo. Let me know if you have any further questions about other regions in the subcortical atlas.
